site_name: Complex Analysis
site_url: https://sandeepsuman.com/complex-analysis/
nav:
  - Home: index.md
  - Fundamentals:
    - 'Definition and Algebra': 'introduction.md'
    - 'Argand Plane': 'plotting.md'
    - 'Complex Functions': 'function.md'
  - Integration:
    - 'Real Functions' : 'real-function.md'
    - 'Contour': 'paths.md'
    - 'Contour Integration': 'integration.md'
    - 'Cauchy Theorem': 'cauchy-theorem.md'
    - 'Cauchy Integral Formula': 'cauchy-integral-formula.md'
    - 'Results Based on CIF': 'results-on-cauchy-integral-formula.md'
    - 'Maximum Modulus Theorem': 'maximum-modulus-theorem.md'
  - Series:
    - 'Power Series': 'power-series.md'
    - 'Taylor Theorem': 'taylor.md'
    - 'Laurent Series': 'laurent.md'
  - Assignments: assignments.md
  - Exam: exam.md
  - Video: video.md

plugins:
  - search
  - minify:
      minify_html: true

  - add-number:
      strict_mode: False
      order: 2
      excludes:
        - index.md


theme:
  palette:
    - scheme: default
      primary: green
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: yellow
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  name: material
  custom_dir: 'theme'
  features:
    - navigation.tabs
    - navigation.top

  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt


  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

  static_templates:
    - 404.html
    
  favicon: 'static/images/favicon.ico'

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

  - meta      


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - static/js/app-local.js

extra_css:
  - 'static/stylesheets/extra.css' # depends on theme


# google_analytics: ['UA-140256543-1', 'sandeepsuman.com']

# Copyright
copyright: 'Copyright &copy; 2016 - 2021 <a href="https://sandeepsuman.com">Sandeep Suman</a>'

extra:
  manifest: 'manifest-local.json'
